services:

    # Spring Boot application service
    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: flox-app
        ports:
            - 8090:8090
            - 5005:5005
        depends_on:
            flox-mysqldb:
                condition: service_healthy
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://flox-mysqldb:3306/FloxDB
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root
            - RUN_MODE=${RUN_MODE:-prod}
        volumes:
            - ./backend:/app
        networks:
            - flox-network

    # MySQL database service
    flox-mysqldb:
        image: mysql:8.0.33
        container_name: flox-mysqldb
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: FloxDB
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./FloxDB_backup.sql:/docker-entrypoint-initdb.d/FloxDB_backup.sql
        networks:
            - flox-network
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            retries: 10
            interval: 3s
            timeout: 30s

volumes:
    mysql-data:

networks:
    flox-network:
        name: flox-network
